# Generated by Django 4.0.5 on 2022-06-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormModel',
            new_name='Contact',
        ),
    ]
