# Generated by Django 4.0.5 on 2022-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('is_available', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
