# Generated by Django 4.0.5 on 2022-06-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
