# Generated by Django 4.0.5 on 2022-06-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sitemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
