# Generated by Django 4.0.5 on 2022-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, default='https://google.com', max_length=1000, null=True),
        ),
    ]
